In [2]:
############################################################
# TEST NB FOR THE IDENTIFY 2.0 SIMULATED ANNEALING LINKING #
############################################################

import pandas 
import numpy
import random

random.seed(777)

#TODO Add variable that decides if we stop at first full_quantity match solution, or search further
#TODO Add overstoch variable

# HYPERSPACE
# the data is sorted by time
# random data
data = [
    [1, 1, "RFNS", 20],
    [2, 1, "RFPS", 100],
    [3, 3, "RFPS", 55],
    [4, 4, "RFNS", 60],
    [5, 5, "RFNS", 25],
    [6, 6, "RFNS", 30],
    [7, 7, "RFNS", 20]
]
# perfect FIFO
# data = [
#     [1, 1, "RFNS", 100],
#     [2, 1, "RFPS", 100],
#     [3, 3, "RFPS", 50],
#     [4, 3, "RFPS", 50],
#     [5, 5, "RFNS", 50],
#     [6, 6, "RFNS", 25],
#     [7, 7, "RFNS", 25]
# ]
df = pandas.DataFrame(data, columns=["TRANSACTION_ID", "TIMESTAMP", "ACTION", "NET_QUANTITY"])

backflushing_penalty = -1000
link_profit = 1
action_that_puts = "RFPS"
action_that_takes = "RFNS"
action_column = "ACTION"
quantity_column = "NET_QUANTITY"
allowed_x_values = [0, 1]

print(df)

   TRANSACTION_ID  TIMESTAMP ACTION  NET_QUANTITY
0               1          1   RFNS            20
1               2          1   RFPS           100
2               3          3   RFPS            55
3               4          4   RFNS            60
4               5          5   RFNS            25
5               6          6   RFNS            30
6               7          7   RFNS            20


In [3]:
# Prepare the data
put_df = df[df[action_column] == action_that_puts].reset_index(drop=True)
take_df = df[df[action_column] == action_that_takes].reset_index(drop=True)
nb_puts = len(put_df.index)
nb_takes = len(take_df.index)

# profit matrix
profits = numpy.full((nb_puts, nb_takes), link_profit, dtype=int)
# Find backflushing examples and correct the profit matrix with backflushing penalties
for put_id, row in put_df.iterrows():
    
    put_timestamp = row["TIMESTAMP"]
    backflushing_take_ids = list(take_df[take_df["TIMESTAMP"] < put_timestamp].index.values)
    
    for take_id in backflushing_take_ids:
        profits[put_id][take_id] = backflushing_penalty

# quantities
put_q = numpy.array(put_df[quantity_column].values)
take_q = numpy.array(take_df[quantity_column].values)

# ids 
put_ids = numpy.array(put_df["TRANSACTION_ID"].values)
take_ids = numpy.array(take_df["TRANSACTION_ID"].values)

# choose initial solution that will be the optimum in case of perfect FIFO
put_cumulative_q = numpy.cumsum(put_q)
take_cumulative_q = numpy.cumsum(take_q)
x = numpy.zeros((nb_puts, nb_takes), dtype=int)
for t_i, t_q in enumerate(take_cumulative_q):
    for p_i, p_q in enumerate(put_cumulative_q):
        if p_q >= t_q:
            x[p_i][t_i] = 1
            break

print(f"put df: {put_df}")
print(f"take df: {take_df}")
print(f"number of puts: {nb_puts}")
print(f"number of takes: {nb_takes}")
print(f"profits: {profits}")
print(f"put quantities: {put_q}")
print(f"take quantities: {take_q}")
print(f"put cumul quantities: {put_cumulative_q}")
print(f"take cumul quantities: {take_cumulative_q}")
print(f"put ids: {put_ids}")
print(f"take ids: {take_ids}")
print(f"x: {x}")
print(numpy.multiply(x[0], take_q))



put df:    TRANSACTION_ID  TIMESTAMP ACTION  NET_QUANTITY
0               2          1   RFPS           100
1               3          3   RFPS            55
take df:    TRANSACTION_ID  TIMESTAMP ACTION  NET_QUANTITY
0               1          1   RFNS            20
1               4          4   RFNS            60
2               5          5   RFNS            25
3               6          6   RFNS            30
4               7          7   RFNS            20
number of puts: 2
number of takes: 5
profits: [[    1     1     1     1     1]
 [-1000     1     1     1     1]]
put quantities: [100  55]
take quantities: [20 60 25 30 20]
put cumul quantities: [100 155]
take cumul quantities: [ 20  80 105 135 155]
put ids: [2 3]
take ids: [1 4 5 6 7]
x: [[1 1 0 0 0]
 [0 0 1 1 1]]
[20 60  0  0  0]


In [4]:

# inequality constraints 
# (Note: limits of the decision variable can be integrated in the generation of a new solution)
# (Source: https://programmer.ink/think/processing-of-python-programming-constraints-of-simulated-annealing-algorithm.html)
# TODO WARNING: The below two tests should be the same if we work with a overstock variable. 
# Then total quantities in and out are always equal, and thus the below two functions are either both True or both False.
def _test_quantity_constraint(x):
    """
    Compare the linked take quantities with the put quantities they come from.
    Linked quantities should never be greater than their corresponding put quantity.

    In principle, we need a full match and only the full match will optimize the objective ftn,
    but to limit calculation times, it may be interesting to accept non-optimal solutions.

    :param x:           the proposed solution
    :return viable:     boolean variable that indicates if the solution is viable
    """
    linked_quantities = numpy.matmul(x, take_q)

    return numpy.less_equal(linked_quantities, put_q).all()

def _test_full_quantity_match(x):
    """
    Compare the linked take quantities with the put quantities they come from.
    If the linked take quantities are equal to to their corresponding put quantity,
    we have a full quantity match.

    :param x:           the proposed solution
    :return full_match: boolean variable that indicates if the solution is perfect
    """
    linked_quantities = numpy.matmul(x, take_q)

    return numpy.array_equal(linked_quantities, put_q)


In [5]:
# CREATE ONE VIABLE SOLUTION - Simulated annealing
def _generate_viable_solution():
    """
    Create a random viable solution. Viable here means quantities """

    #TODO calculate some new solution
    x_new = numpy.zeros((nb_puts, nb_takes), dtype=int)
    for t_i in range(nb_takes):
        p_i = random.randint(0, nb_puts-1)
        x_new[p_i][t_i] = 1

    # test the solution
    viable_solution = _test_quantity_constraint(x_new)
    # print("----------------------------------------------")
    # print(f"New solution proposed: {x_new}")
    # print(f"This solution is viable? {viable_solution}.")
    # print("----------------------------------------------")

    if not viable_solution:
        _generate_viable_solution()
    
    return x_new
    
# TODO Remove this test code
for i in range(10):
    x = _generate_viable_solution()
    # print(f"------------------------------- Round {i+1} ----------------------------------")
    # print(f"PROPOSED VIABLE SOLUTION: {x}")
    # print("------------------------------------------------------------------------------")


In [6]:
# SIMULATED ANNEALING
# Iteratively create viable solutions with the above function, and then find the one that optimizes a goal function
# TODO QUESTION: What is the goal function.... How do we choose one option over the other? See Joris' goal function(s)
#       - Calculate some 'similarity' metrics: 
#               Total timedifference, number of subbatch groups, number of intermediate neighbors, ... (see written notebook)

def _simulated_annealing(x_old):

    # this is the core algotithm

    #TODO Create a viable solution with the previous function
    x_new = _generate_viable_solution(x_old)
    #(Not sure abt this one)TODO In case we have a perfect quantity match, return the solution and end the algo
    if _test_full_quantity_match(x_new):
        return x_new
    #TODO Calculate profit
    #TODO Follow simulated annealing principles to choose between solutions and repeat the loop
    #(interesting: https://programmer.ink/think/processing-of-python-programming-constraints-of-simulated-annealing-algorithm.html)

def apply():
    return None

In [15]:
# playground
a = numpy.array([1, 2, 3, 5, 8, 10])
x = numpy.array([[0,1,0,0,1],[1,0,1,1,0]])
b = numpy.mod(100, a)
non_zeros = numpy.count_nonzero(b)
print(b)
print(1 - non_zeros / b.size)


[0 0 1 0 4 0]
0.6666666666666667
0.6
